
# Trainer config
max_steps: -1  # -1 means unlimited (controlled by max_epochs)
max_epochs: 200
num_sanity_val_steps: 1
log_every_n_steps: 10
val_check_interval: null
check_val_every_n_epoch: 1
deterministic: True
accumulate_grad_batches: 2
precision: 32 # full | 16-mixed | bf16 | bf16-mixed
benchmark: true
gradient_clip_val: 5.0
accelerator: gpu
devices: 1
strategy: auto # auto, ddp, ddp_spawn, deepspeed
