
# Trainer config
max_steps: 1000  # Default max steps, can be overridden
max_epochs: null  # Set to null when using max_steps
num_sanity_val_steps: 1
log_every_n_steps: 10
val_check_interval: 50  # Run validation every 50 steps
check_val_every_n_epoch: 1
deterministic: False
accumulate_grad_batches: 1
precision: 32 # full | 16-mixed | bf16 | bf16-mixed
benchmark: true
gradient_clip_val: 5.0
accelerator: gpu
devices: 1
