# This is the standard configuration file for pre-commit hooks.
# It helps catch and fix issues automatically before code is even committed.
# To use, run `pre-commit install` in your local repository.
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # Using a more recent version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: mkdocs\.yml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Run Ruff's formatter and linter.
    rev: v0.5.0 # Using a more recent version
    hooks:
      - id: ruff
        name: ruff-linter-fixer
        args: [--fix, --unsafe-fixes, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1 # Using a more recent version
    hooks:
      - id: mypy
        # You can customize args and dependencies to match your project's needs
        additional_dependencies: [types-Pillow, types-tqdm, types-PyYAML, types-shapely]
        files: ^ocr/

  - repo: local
    hooks:
      - id: validate-handbook-manifest
        name: validate-handbook-manifest
        entry: uv run python scripts/agent_tools/validate_manifest.py
        language: system
        pass_filenames: false
