# @package model

architecture_name: craft
component_overrides:
  encoder:
    pretrained: true
    output_indices: [1, 2, 3, 4]
  decoder:
    inner_channels: 256
    out_channels: 256
  head:
    hidden_channels: 128

optimizer:
  _target_: torch.optim.Adam
  lr: 0.0005
  weight_decay: 0.0001
scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  step_size: 100
  gamma: 0.1
