# @package model

defaults:
  - /model/architectures: dbnetpp
  - /model/optimizers: adamw
  - /preset/models/encoder/timm_backbone
  - /preset/models/decoder/dbpp_decoder
  - /preset/models/head/db_head
  - /preset/models/loss/db_loss
  - _self_

component_overrides:
  encoder:
    model_name: "resnet50"
    select_features: [1, 2, 3, 4]
    pretrained: true
  decoder:
    inner_channels: 256
    out_channels: 128
  head:
    upscale: 4

optimizer:
  lr: 0.0003
  weight_decay: 0.0001

# Scheduler is now defined in the base model config
