# https://hydra.cc/docs/configure_hydra/intro/

# enable color logging
defaults:
  - _self_

# output directory, generated dynamically on each run
run:
  dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
sweep:
  dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
  subdir: ${hydra.job.num}

job:
  chdir: true

job_logging:
  handlers:
    file:
      # Incorporates fix from https://github.com/facebookresearch/hydra/pull/2242
      filename: ${hydra.runtime.output_dir}/${task_name}.log
