# @package model

architecture_name: craft

component_overrides:
  encoder:
    model_name: "vgg16_bn"
    pretrained: true
    output_indices: [1, 2, 3, 4]
    extra_channels: 512
    freeze_backbone: false
  decoder:
    inner_channels: 256
    out_channels: 256
  head:
    hidden_channels: 128
  loss:
    region_weight: 1.0
    affinity_weight: 1.0
