# @package model

architecture_name: dbnetpp

component_overrides:
  encoder:
    model_name: "resnet50"
    select_features: [1, 2, 3, 4]
    pretrained: true
  decoder:
    name: "dbnetpp_decoder"
    params:
      inner_channels: 256
      out_channels: 128
  head:
    name: "dbnetpp_head"
    params:
      upscale: 4
  loss:
    name: "dbnetpp_loss"
    params:
      negative_ratio: 3.0
      prob_map_loss_weight: 5.0
      thresh_map_loss_weight: 10.0
      binary_map_loss_weight: 1.0
