# Canonical compatibility definitions for OCR inference checkpoints.
# Each family describes a compatible combination of encoder, decoder, and head settings.

model_families:
  - id: dbnet_resnet18_unet64
    description: "DBNet architecture trained with ResNet18 backbone and UNet decoder producing 64-channel maps."
    encoder:
      model_names: ["resnet18"]
    decoder:
      class: ocr.models.decoder.UNet
      inner_channels: 256
      output_channels: 64
      in_channels: [64, 128, 256, 512]
    head:
      class: ocr.models.head.DBHead
      in_channels: 256
  - id: dbnet_resnet18_unet256
    description: "DBNet architecture trained with ResNet18 backbone and UNet decoder widened to 256 output channels."
    encoder:
      model_names: ["resnet18"]
    decoder:
      class: ocr.models.decoder.UNet
      inner_channels: 256
      output_channels: 256
      in_channels: [64, 128, 256, 512]
    head:
      class: ocr.models.head.DBHead
      in_channels: 256
  - id: dbnet_mobilenetv3_small_unet256
    description: "DBNet architecture trained with MobileNetV3 Small backbone and widened UNet decoder."
    encoder:
      model_names: ["mobilenetv3_small_050"]
    decoder:
      class: ocr.models.decoder.UNet
      inner_channels: 256
      output_channels: 256
      in_channels: [8, 16, 24, 288]
    head:
      class: ocr.models.head.DBHead
      in_channels: 256
