# Logger config
wandb:
  enabled: True
project_name: "receipt-text-recognition-ocr-project"
exp_version: "v1.0"

# Per batch image logging for error analysis
per_batch_image_logging:
  enabled: false
  recall_threshold: 0.4
  max_batches_per_epoch: 2
  max_images_per_batch: 4
  use_transformed_batch: true
  image_format: jpeg
  max_image_side: 640
