# @package _global_

# Default interpolation method for performance optimization
# 1 = cv2.INTER_LINEAR (faster), 3 = cv2.INTER_CUBIC (higher quality)
default_interpolation: 1

transforms:
  train_transform:
    _target_: ${dataset_path}.DBTransforms
    transforms:
      - _target_: albumentations.LongestMaxSize
        max_size: 640
        interpolation: ${default_interpolation}
        p: 1.0
      - _target_: albumentations.PadIfNeeded
        min_width: 640
        min_height: 640
        border_mode: 0
        p: 1.0
      - _target_: albumentations.HorizontalFlip
        p: 0.5
      - _target_: albumentations.Normalize
        mean: [0.5602, 0.5602, 0.5602]
        std: [0.2539, 0.2539, 0.2539]
    keypoint_params:
      _target_: albumentations.KeypointParams
      format: 'xy'
      remove_invisible: True
  val_transform:
    _target_: ${dataset_path}.DBTransforms
    transforms:
      - _target_: albumentations.LongestMaxSize
        max_size: 640
        interpolation: ${default_interpolation}
        p: 1.0
      - _target_: albumentations.PadIfNeeded
        min_width: 640
        min_height: 640
        border_mode: 0
        p: 1.0
      - _target_: albumentations.Normalize
        mean: [0.5602, 0.5602, 0.5602]
        std: [0.2539, 0.2539, 0.2539]
    keypoint_params:
      _target_: albumentations.KeypointParams
      format: 'xy'
      remove_invisible: True
  test_transform:
    _target_: ${dataset_path}.DBTransforms
    transforms:
      - _target_: albumentations.LongestMaxSize
        max_size: 640
        interpolation: ${default_interpolation}
        p: 1.0
      - _target_: albumentations.PadIfNeeded
        min_width: 640
        min_height: 640
        border_mode: 0
        p: 1.0
      - _target_: albumentations.Normalize
        mean: [0.5602, 0.5602, 0.5602]
        std: [0.2539, 0.2539, 0.2539]
    keypoint_params:
      _target_: albumentations.KeypointParams
      format: 'xy'
      remove_invisible: True
  predict_transform:
    _target_: ${dataset_path}.DBTransforms
    transforms:
      - _target_: albumentations.LongestMaxSize
        max_size: 640
        interpolation: ${default_interpolation}
        p: 1.0
      - _target_: albumentations.PadIfNeeded
        min_width: 640
        min_height: 640
        border_mode: 0
        p: 1.0
      - _target_: albumentations.Normalize
        mean: [0.5602, 0.5602, 0.5602]
        std: [0.2539, 0.2539, 0.2539]
    keypoint_params: null
