# @package _global_

# Example configuration showing how to integrate background removal
# into your OCR preprocessing pipeline

# Import base transforms
defaults:
  - base

# Override transforms to include background removal
transforms:
  # Training transform with background removal
  train_transform:
    _target_: ${dataset_path}.DBTransforms
    transforms:
      # Background removal should be applied early in the pipeline
      - _target_: ocr.datasets.preprocessing.external.BackgroundRemoval
        model: "u2net"
        alpha_matting: true
        p: 1.0  # Apply to all training images
      - _target_: albumentations.LongestMaxSize
        max_size: 640
        interpolation: ${default_interpolation}
        p: 1.0
      - _target_: albumentations.PadIfNeeded
        min_width: 640
        min_height: 640
        border_mode: 0
        p: 1.0
      - _target_: albumentations.HorizontalFlip
        p: 0.5
      - _target_: albumentations.Normalize
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    keypoint_params:
      _target_: albumentations.KeypointParams
      format: 'xy'
      remove_invisible: True

  # Validation transform with background removal
  val_transform:
    _target_: ${dataset_path}.DBTransforms
    transforms:
      - _target_: ocr.datasets.preprocessing.external.BackgroundRemoval
        model: "u2net"
        alpha_matting: true
        p: 1.0
      - _target_: albumentations.LongestMaxSize
        max_size: 640
        interpolation: ${default_interpolation}
        p: 1.0
      - _target_: albumentations.PadIfNeeded
        min_width: 640
        min_height: 640
        border_mode: 0
        p: 1.0
      - _target_: albumentations.Normalize
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    keypoint_params:
      _target_: albumentations.KeypointParams
      format: 'xy'
      remove_invisible: True

  # Test transform with background removal
  test_transform:
    _target_: ${dataset_path}.DBTransforms
    transforms:
      - _target_: ocr.datasets.preprocessing.external.BackgroundRemoval
        model: "u2net"
        alpha_matting: true
        p: 1.0
      - _target_: albumentations.LongestMaxSize
        max_size: 640
        interpolation: ${default_interpolation}
        p: 1.0
      - _target_: albumentations.PadIfNeeded
        min_width: 640
        min_height: 640
        border_mode: 0
        p: 1.0
      - _target_: albumentations.Normalize
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    keypoint_params:
      _target_: albumentations.KeypointParams
      format: 'xy'
      remove_invisible: True

  # Prediction transform with background removal
  predict_transform:
    _target_: ${dataset_path}.DBTransforms
    transforms:
      - _target_: ocr.datasets.preprocessing.external.BackgroundRemoval
        model: "u2net"
        alpha_matting: true
        p: 1.0
      - _target_: albumentations.LongestMaxSize
        max_size: 640
        interpolation: 1
        p: 1.0
      - _target_: albumentations.PadIfNeeded
        min_width: 640
        min_height: 640
        border_mode: 0
        p: 1.0
      - _target_: albumentations.Normalize
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    keypoint_params: null
