
# Paths config - Timestamp-based structure for reliability
experiment_dir: 'outputs'
log_dir: '${hydra:runtime.output_dir}/logs'
output_dir: '${hydra:runtime.output_dir}'
checkpoint_dir: '${hydra:runtime.output_dir}/checkpoints'
submission_dir: '${hydra:runtime.output_dir}/submissions'
