# @package _global_
# Quick preset that enables the docTR-enhanced preprocessing stack so you can
# compare "before vs after" in one command:
#   uv run python runners/predict.py preset.datasets=preprocessing_docTR_demo
# Or to switch training presets:
#   uv run python runners/train.py preset.datasets=preprocessing_docTR_demo

preprocessing:
  enable_document_detection: true
  enable_perspective_correction: true
  enable_enhancement: true
  enhancement_method: "office_lens"
  enable_text_enhancement: true
  target_size: [640, 640]
  enable_final_resize: false

  enable_orientation_correction: true
  orientation_angle_threshold: 1.0
  orientation_expand_canvas: true
  orientation_preserve_original_shape: false

  use_doctr_geometry: true
  doctr_assume_horizontal: false

  enable_padding_cleanup: true
  document_detection_min_area_ratio: 0.12
  document_detection_use_adaptive: true
  document_detection_use_fallback_box: true

lens_style_preprocessor:
  _target_: ${dataset_path}.LensStylePreprocessorAlbumentations
  preprocessor:
    _target_: ${dataset_path}.DocumentPreprocessor
    enable_document_detection: ${preprocessing.enable_document_detection}
    enable_perspective_correction: ${preprocessing.enable_perspective_correction}
    enable_enhancement: ${preprocessing.enable_enhancement}
    enhancement_method: ${preprocessing.enhancement_method}
    enable_text_enhancement: ${preprocessing.enable_text_enhancement}
    target_size: ${preprocessing.target_size}
    enable_final_resize: ${preprocessing.enable_final_resize}
    enable_orientation_correction: ${preprocessing.enable_orientation_correction}
    orientation_angle_threshold: ${preprocessing.orientation_angle_threshold}
    orientation_expand_canvas: ${preprocessing.orientation_expand_canvas}
    orientation_preserve_original_shape: ${preprocessing.orientation_preserve_original_shape}
    use_doctr_geometry: ${preprocessing.use_doctr_geometry}
    doctr_assume_horizontal: ${preprocessing.doctr_assume_horizontal}
    enable_padding_cleanup: ${preprocessing.enable_padding_cleanup}
    document_detection_min_area_ratio: ${preprocessing.document_detection_min_area_ratio}
    document_detection_use_adaptive: ${preprocessing.document_detection_use_adaptive}
    document_detection_use_fallback_box: ${preprocessing.document_detection_use_fallback_box}

# Reuse the enhanced transform definitions from the base preset but hook in the
# docTR preprocessor first so Albumentations sees rectified images.
enhanced_transforms:
  train_transform:
    _target_: ${dataset_path}.DBTransforms
    transforms:
      - ${lens_style_preprocessor}
      - _target_: albumentations.HorizontalFlip
        p: 0.5
      - _target_: albumentations.Normalize
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    keypoint_params:
      _target_: albumentations.KeypointParams
      format: 'xy'
      remove_invisible: True

  val_transform:
    _target_: ${dataset_path}.DBTransforms
    transforms:
      - ${lens_style_preprocessor}
      - _target_: albumentations.Normalize
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    keypoint_params:
      _target_: albumentations.KeypointParams
      format: 'xy'
      remove_invisible: True

  test_transform:
    _target_: ${dataset_path}.DBTransforms
    transforms:
      - ${lens_style_preprocessor}
      - _target_: albumentations.Normalize
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    keypoint_params:
      _target_: albumentations.KeypointParams
      format: 'xy'
      remove_invisible: True

  predict_transform:
    _target_: ${dataset_path}.DBTransforms
    transforms:
      - ${lens_style_preprocessor}
    keypoint_params: null
