# Preprocessing Configuration
# Microsoft Lens-style document preprocessing

preprocessing:
  # --- DocumentDetector ---------------------------------------------------
  enable_document_detection: true
  document_detection_min_area_ratio: 0.18
  document_detection_use_adaptive: true
  document_detection_use_fallback_box: true

  # --- PerspectiveCorrector -----------------------------------------------
  enable_perspective_correction: true
  use_doctr_geometry: false          # Switch to docTR rcrops when available
  doctr_assume_horizontal: false

  # --- OrientationCorrector -----------------------------------------------
  enable_orientation_correction: false
  orientation_angle_threshold: 2.0
  orientation_expand_canvas: true
  orientation_preserve_original_shape: false

  # --- PaddingCleanup -----------------------------------------------------
  enable_padding_cleanup: false

  # --- ImageEnhancer / TextEnhancer ---------------------------------------
  enable_enhancement: true
  enhancement_method: "conservative"  # "conservative" or "office_lens"
  enable_text_enhancement: false

  # --- FinalResizer -------------------------------------------------------
  target_size: [640, 640]
  enable_final_resize: true

# Albumentations-compatible preprocessor
lens_style_preprocessor:
  _target_: ${dataset_path}.LensStylePreprocessorAlbumentations
  preprocessor:
    _target_: ${dataset_path}.DocumentPreprocessor
    enable_document_detection: ${preprocessing.enable_document_detection}
    enable_perspective_correction: ${preprocessing.enable_perspective_correction}
    enable_enhancement: ${preprocessing.enable_enhancement}
    enhancement_method: ${preprocessing.enhancement_method}
    enable_text_enhancement: ${preprocessing.enable_text_enhancement}
    target_size: ${preprocessing.target_size}
    enable_final_resize: ${preprocessing.enable_final_resize}
    enable_orientation_correction: ${preprocessing.enable_orientation_correction}
    orientation_angle_threshold: ${preprocessing.orientation_angle_threshold}
    orientation_expand_canvas: ${preprocessing.orientation_expand_canvas}
    orientation_preserve_original_shape: ${preprocessing.orientation_preserve_original_shape}
    use_doctr_geometry: ${preprocessing.use_doctr_geometry}
    doctr_assume_horizontal: ${preprocessing.doctr_assume_horizontal}
    enable_padding_cleanup: ${preprocessing.enable_padding_cleanup}
    document_detection_min_area_ratio: ${preprocessing.document_detection_min_area_ratio}
    document_detection_use_adaptive: ${preprocessing.document_detection_use_adaptive}
    document_detection_use_fallback_box: ${preprocessing.document_detection_use_fallback_box}

# Enhanced transforms with preprocessing
enhanced_transforms:
  train_transform:
    _target_: ${dataset_path}.DBTransforms
    transforms:
      - ${lens_style_preprocessor}
      - _target_: albumentations.HorizontalFlip
        p: 0.5
      - _target_: albumentations.Normalize
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    keypoint_params:
      _target_: albumentations.KeypointParams
      format: 'xy'
      remove_invisible: True

  val_transform:
    _target_: ${dataset_path}.DBTransforms
    transforms:
      - ${lens_style_preprocessor}
      - _target_: albumentations.Normalize
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    keypoint_params:
      _target_: albumentations.KeypointParams
      format: 'xy'
      remove_invisible: True

  test_transform:
    _target_: ${dataset_path}.DBTransforms
    transforms:
      - ${lens_style_preprocessor}
      - _target_: albumentations.Normalize
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    keypoint_params:
      _target_: albumentations.KeypointParams
      format: 'xy'
      remove_invisible: True

  predict_transform:
    _target_: ${dataset_path}.DBTransforms
    transforms:
      - ${lens_style_preprocessor}

# Office Lens enhanced preprocessor (more sophisticated enhancement)
lens_style_preprocessor_office_lens:
  _target_: ${dataset_path}.LensStylePreprocessorAlbumentations
  preprocessor:
    _target_: ${dataset_path}.DocumentPreprocessor
    enable_document_detection: ${preprocessing.enable_document_detection}
    enable_perspective_correction: ${preprocessing.enable_perspective_correction}
    enable_enhancement: ${preprocessing.enable_enhancement}
    enhancement_method: "office_lens"
    enable_text_enhancement: ${preprocessing.enable_text_enhancement}
    target_size: ${preprocessing.target_size}
    enable_final_resize: ${preprocessing.enable_final_resize}
    enable_orientation_correction: ${preprocessing.enable_orientation_correction}
    orientation_angle_threshold: ${preprocessing.orientation_angle_threshold}
    orientation_expand_canvas: ${preprocessing.orientation_expand_canvas}
    orientation_preserve_original_shape: ${preprocessing.orientation_preserve_original_shape}
    use_doctr_geometry: ${preprocessing.use_doctr_geometry}
    doctr_assume_horizontal: ${preprocessing.doctr_assume_horizontal}
    enable_padding_cleanup: ${preprocessing.enable_padding_cleanup}
    document_detection_min_area_ratio: ${preprocessing.document_detection_min_area_ratio}
    document_detection_use_adaptive: ${preprocessing.document_detection_use_adaptive}
    document_detection_use_fallback_box: ${preprocessing.document_detection_use_fallback_box}
