# This file defines the callbacks that will be instantiated by Hydra.
# The `defaults` section includes individual callback configurations.
# Custom callbacks that don't have separate files are defined below.

defaults:
  - model_checkpoint
  - early_stopping
  - rich_progress_bar
  - _self_

wandb_completion:
  _target_: ocr.lightning_modules.callbacks.wandb_completion.WandbCompletionCallback

wandb_image_logging:
  _target_: ocr.lightning_modules.callbacks.wandb_image_logging.WandbImageLoggingCallback
  log_every_n_epochs: 5
