# Default callbacks configuration
# Add common callbacks here that should be enabled by default

defaults: []

# Example of how to include callbacks by default
# This can be overridden by specific experiments
