# This file defines the callbacks that will be instantiated by Hydra.
# The `_target_` key tells Hydra which Python class to create.
# We use variable interpolation (e.g., ${paths.checkpoint_dir}) to reference
# other parts of the main configuration tree.

model_checkpoint:
  _target_: ocr.lightning_modules.callbacks.unique_checkpoint.UniqueModelCheckpoint
  dirpath: ${paths.checkpoint_dir}
  filename: "epoch_{epoch:02d}_step_{step:06d}"
  monitor: "val_loss"
  mode: "min"
  save_top_k: 1
  save_last: true
  add_timestamp: true

early_stopping:
  _target_: lightning.pytorch.callbacks.EarlyStopping
  monitor: "val_loss"
  patience: 5
  mode: "min"

wandb_completion:
  _target_: ocr.lightning_modules.callbacks.wandb_completion.WandbCompletionCallback

wandb_image_logging:
  _target_: ocr.lightning_modules.callbacks.wandb_image_logging.WandbImageLoggingCallback
  log_every_n_epochs: 5
