profiler:
  _target_: ocr.callbacks.profiler.ProfilerCallback
  enabled: false  # Disabled by default (performance overhead)
  profile_epochs: [1]  # Only profile first epoch
  profile_steps: 10  # Much fewer steps to avoid memory issues
  warmup_steps: 2
  activities: ["cuda"]  # Only GPU profiling (CPU profiling is too slow)
  record_shapes: false  # Disable shape recording (massive memory usage)
  with_stack: false  # Keep disabled for performance
  output_dir: "profiler_traces"
  export_chrome_trace: true
  log_top_k_ops: 15
