resource_monitor:
  _target_: ocr.callbacks.resource_monitor.ResourceMonitorCallback
  enabled: true
  log_interval: 10  # Log every 10 batches
  gpu_monitoring: true
  cpu_monitoring: true
  io_monitoring: true
  alert_gpu_underutilization: true
  alert_memory_pressure: true
  alert_io_bottleneck: true
  gpu_util_threshold: 0.5  # Alert if GPU <50%
  memory_threshold: 0.9  # Alert if memory >90%
  io_wait_threshold: 0.3  # Alert if >30% I/O wait
  export_timeseries: true
  timeseries_path: "resource_logs"
