hydra:
  run:
    dir: 'outputs/${exp_name}'

# Task name for hydra logging
task_name: "train"

defaults:
  - model: default
  - metrics: cleval
  - paths: default
  - logger: default
  - trainer: default
  - callbacks: default
  - debug: default
  - hydra: default
  - extras: default

dataset_module: ocr.datasets
dataset_config_module: ocr.datasets.schemas

# Model and component paths
dataset_path: ${dataset_module}
dataset_config_path: ${dataset_config_module}
model_path: ocr.models
encoder_path: ocr.models.encoder
decoder_path: ocr.models.decoder
head_path: ocr.models.head
loss_path: ocr.models.loss
lightning_path: ocr.lightning_modules
