defaults:
  - _self_
  - base                  # Keep for other settings
  - data: base            # Compose data group
  - transforms: base      # Compose transforms group
  - dataloaders: default  # Compose dataloaders group
  - /preset/models/model_example
  - /preset/lightning_modules/base
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

seed: 42
exp_name: "ocr_prediction"
checkpoint_path: "outputs/ocr_training-dbnet-pan_decoder-resnet34/checkpoints/epoch_28_step_023722.ckpt" # resnet18 · step_014454 works too
image_dir: "LOW_PERFORMANCE_IMGS"
max_images: 1
score_threshold: 0.01
save_dir: "outputs/prediction_visualization"
minified_json: False
include_confidence: False

# Optional overrides for DB postprocessor thresholds
postprocess_thresh: null
postprocess_box_thresh: null
postprocess_max_candidates: null
postprocess_use_polygon: null
