defaults:
  - _self_
  - base                  # Keep for other settings
  - data: base            # Compose data group
  - data/performance_preset: none  # Default performance preset (no optimizations)
  - transforms: base      # Compose transforms group
  - dataloaders: default  # Compose dataloaders group
  - /preset/models/model_example
  - /preset/lightning_modules/base

# Override callbacks to match the checkpoint
callbacks:
  model_checkpoint:
    _target_: lightning.pytorch.callbacks.ModelCheckpoint
    monitor: "val/loss"
    mode: "min"
    every_n_train_steps: 0
    every_n_epochs: 1
    train_time_interval: null

compile_model: false

seed: 42
exp_name: "ocr_prediction_shadow_removal"
checkpoint_path: "outputs/new_norm_receipt_filter-dbnet-unet-mobilenetv3_small_050-unknown_training_20251016_231633/checkpoints/best.ckpt"
image_dir: "test_shadow_removed"
max_images: 1
score_threshold: 0.01
save_dir: "outputs/prediction_shadow_removal"
minified_json: False
include_confidence: False

datasets:
  predict_dataset:
    _target_: ${dataset_path}.ValidatedOCRDataset
    config:
      _target_: ${dataset_config_path}.DatasetConfig
      image_path: ${image_dir}
      annotation_path: null
    transform: ${transforms.test_transform}
