defaults:
  - _self_
  - preset:
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

seed: 42
exp_name: "ocr_training"

checkpoint_path: "outputs/ocr_training/checkpoints/epoch-0-step-205.ckpt"
minified_json: False
