defaults:
  - _self_
  - base
  - preset/models/model_example
  - preset/lightning_modules/base
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

seed: 42
exp_name: "ocr_prediction"
checkpoint_path: "outputs/ocr_training/checkpoints/epoch-0-step-205.ckpt"
minified_json: False
include_confidence: False
