defaults:
  - _self_
  - base                  # Keep for other settings
  - data: base            # Compose data group
  - transforms: base      # Compose transforms group
  - dataloaders: default  # Compose dataloaders group
  - /preset/models/model_example
  - /preset/lightning_modules/base
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

seed: 42
exp_name: "ocr_training"
checkpoint_path: null
