defaults:
  - _self_
  - base
  - preset/models/model_example
  - preset/lightning_modules/base
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

seed: 42
exp_name: "ocr_training"
resume: null
project_name: null
experiment_tag: null
wandb: false

callbacks: {}
