defaults:
  - _self_
  - base                  # Keep for other settings
  - data: base            # Compose data group
  - transforms: base      # Compose transforms group
  - dataloaders: default  # Compose dataloaders group
  - /preset/models/model_example
  - /preset/lightning_modules/base

seed: 42
exp_name: "ocr_training"
resume: null
project_name: null
experiment_tag: null
wandb: true

# Remove this line to use default callbacks (including wandb_image_logging)
# callbacks: {}

runtime:
  auto_gpu_devices: true
  ddp_strategy: ddp_find_unused_parameters_false
  min_auto_devices: 2
