defaults:
  - _self_
  - base                  # Keep for other settings
  - data: base            # Compose data group
  - transforms: base      # Compose transforms group
  - dataloaders: default  # Compose dataloaders group
  - callbacks: default    # Compose callbacks group
  - experiment: synthetic_debug  # Default experiment configuration
  - /preset/models/model_example
  - /preset/lightning_modules/base

seed: 42
exp_name: "ocr_training"
resume: null
project_name: null
experiment_tag: null
wandb: true

# Callbacks are now configured via callbacks/default.yaml
# Individual experiments can override with +callbacks.specific_callback.enabled=true/false

runtime:
  auto_gpu_devices: true
  ddp_strategy: ddp_find_unused_parameters_false
  min_auto_devices: 2
