# Batch Size Ablation Study
# Usage: python run_ablation.py +ablation=batch_size -m

# @package _global_

defaults:
  - _self_

hydra:
  sweeper:
    params:
      data.batch_size: 4,8,16,32
      model.optimizer.lr: 1e-3,2e-3,4e-3,8e-3
      trainer.max_steps: 2000,4000

# Keep epochs modest for quicker iteration across combinations.
trainer:
  max_epochs: 5

# Enable wandb logging for ablation runs and tag outputs consistently.
wandb: true
experiment_tag: "batch_size_ablation"
