# @package model.loss

# https://arxiv.org/pdf/1911.08947.pdf 참조

_target_: ${loss_path}.DBLoss
negative_ratio: 3.0
eps: 1e-6
prob_map_loss_weight: 5.0
thresh_map_loss_weight: 10.0
binary_map_loss_weight: 1.0
