name: CI

on:
  push:
    branches: [ "00_refactor/baseline" ]
  pull_request:
    branches: [ "00_refactor/baseline" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install uv
        uses: astral-sh/setup-uv@v1

      - name: Cache uv dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml', '**/uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install dependencies
        run: uv pip sync pyproject.toml -- --all-extras

      - name: Format check with black
        run: uv run black --check --diff .

      - name: Import sorting check with isort
        run: uv run isort --check-only --diff .

      - name: Type check with mypy
        run: uv run mypy ocr/

      - name: Run tests
        run: uv run pytest tests/ -v